version: "2"

services:
  jekyll:
    environment:
      - PAGES_REPO_NWO=omakoleg/typescript-practices
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - ./docs:/srv/jekyll
